name: chat-gpt
options:
  bundleIdPrefix: com.example
  developmentLanguage: en
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.chatgpt
    PRODUCT_NAME: chat-gpt
    SWIFT_VERSION: 5
    MARKETING_VERSION: 1
    CURRENT_PROJECT_VERSION: 1
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    SUPPORTS_MACCATALYST: 'NO'
    ALWAYS_SEARCH_USER_PATHS: 'NO'
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
targets:
  chat-gpt:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - path: chat-gpt
    info:
      path: chat-gpt/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: 6
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    dependencies: []
schemes:
  chat-gpt:
    build:
      targets:
        chat-gpt: all
    run:
      config: Debug
      storeKitConfiguration: chat-gpt/Store/AndiProducts.storekit
    archive:
      config: Release
packages: {}
